@startuml

'https://plantuml.com/class-diagram

class app41 {
    + (LinkedList <String>)List: namesList
    + stringBuilder(LinkedList <String>)
    + alphabetize(LinkedList <String>))
}

class txtHandler {
    + readTxt(filename)
    + writeTxt(string)
    + createFile(filename
}


app41 o--> txtHandler



@enduml