@startuml
'https://plantuml.com/sequence-diagram

class App45{
    + main()
    + getReplacedText()
}
class fileHandler{
    + readFile()
    + createFile()
    + writeNewFile()
}
App45 *-- fileHandler
@enduml